// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-target/internal/sdk/models/shared"
	"net/http"
)

type CreateTargetResponse struct {
	// Any error based on client data errors
	ClientError *shared.ClientError
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Target entity response
	Target *shared.Target
}

func (c *CreateTargetResponse) GetClientError() *shared.ClientError {
	if c == nil {
		return nil
	}
	return c.ClientError
}

func (c *CreateTargetResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateTargetResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateTargetResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateTargetResponse) GetTarget() *shared.Target {
	if c == nil {
		return nil
	}
	return c.Target
}
