// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-target/internal/sdk/models/shared"
	"net/http"
)

type PatchTargetRequest struct {
	// Target to patch
	TargetPatch shared.TargetPatch `request:"mediaType=application/json"`
	// The target id
	TargetID string `pathParam:"style=simple,explode=false,name=targetId"`
}

func (o *PatchTargetRequest) GetTargetPatch() shared.TargetPatch {
	if o == nil {
		return shared.TargetPatch{}
	}
	return o.TargetPatch
}

func (o *PatchTargetRequest) GetTargetID() string {
	if o == nil {
		return ""
	}
	return o.TargetID
}

type PatchTargetResponse struct {
	// Any error based on client data errors
	ClientError *shared.ClientError
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Target entity response
	Target *shared.Target
}

func (o *PatchTargetResponse) GetClientError() *shared.ClientError {
	if o == nil {
		return nil
	}
	return o.ClientError
}

func (o *PatchTargetResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchTargetResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchTargetResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PatchTargetResponse) GetTarget() *shared.Target {
	if o == nil {
		return nil
	}
	return o.Target
}
