// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// BaseEntityACL - Access control list (ACL) for an entity. Defines sharing access to external orgs or users.
type BaseEntityACL struct {
	Delete []string `json:"delete,omitempty"`
	Edit   []string `json:"edit,omitempty"`
	View   []string `json:"view,omitempty"`
}

func (b *BaseEntityACL) GetDelete() []string {
	if b == nil {
		return nil
	}
	return b.Delete
}

func (b *BaseEntityACL) GetEdit() []string {
	if b == nil {
		return nil
	}
	return b.Edit
}

func (b *BaseEntityACL) GetView() []string {
	if b == nil {
		return nil
	}
	return b.View
}
