// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type TargetCreateSchema string

const (
	TargetCreateSchemaTarget TargetCreateSchema = "target"
)

func (e TargetCreateSchema) ToPointer() *TargetCreateSchema {
	return &e
}
func (e *TargetCreateSchema) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "target":
		*e = TargetCreateSchema(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TargetCreateSchema: %v", v)
	}
}

type TargetCreate struct {
	// Additional fields that are not part of the schema
	Additional map[string]any `json:"__additional,omitempty"`
	Files      *BaseRelation  `json:"_files,omitempty"`
	// Manifest ID used to create/update the entity
	Manifest []string            `json:"_manifest,omitempty"`
	Purpose  []string            `json:"_purpose,omitempty"`
	Schema   *TargetCreateSchema `json:"_schema,omitempty"`
	Tags     []string            `json:"_tags,omitempty"`
	// The description of the target
	Description *string `json:"description,omitempty"`
	// The filters on the targeted schema
	EntityFilters any `json:"entity_filters,omitempty"`
	// The schema of the target entities
	EntitySchema *string `json:"entity_schema,omitempty"`
	// The description for the target
	Name string `json:"name"`
}

func (t *TargetCreate) GetAdditional() map[string]any {
	if t == nil {
		return nil
	}
	return t.Additional
}

func (t *TargetCreate) GetFiles() *BaseRelation {
	if t == nil {
		return nil
	}
	return t.Files
}

func (t *TargetCreate) GetManifest() []string {
	if t == nil {
		return nil
	}
	return t.Manifest
}

func (t *TargetCreate) GetPurpose() []string {
	if t == nil {
		return nil
	}
	return t.Purpose
}

func (t *TargetCreate) GetSchema() *TargetCreateSchema {
	if t == nil {
		return nil
	}
	return t.Schema
}

func (t *TargetCreate) GetTags() []string {
	if t == nil {
		return nil
	}
	return t.Tags
}

func (t *TargetCreate) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TargetCreate) GetEntityFilters() any {
	if t == nil {
		return nil
	}
	return t.EntityFilters
}

func (t *TargetCreate) GetEntitySchema() *string {
	if t == nil {
		return nil
	}
	return t.EntitySchema
}

func (t *TargetCreate) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}
