// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"github.com/epilot-dev/terraform-provider-epilot-target/internal/provider/typeconvert"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-target/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-target/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-target/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *TargetDataSourceModel) RefreshFromSharedTarget(ctx context.Context, resp *shared.Target) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if resp.Additional != nil {
			r.Additional = make(map[string]jsontypes.Normalized, len(resp.Additional))
			for key, value := range resp.Additional {
				result, _ := json.Marshal(value)
				r.Additional[key] = jsontypes.NewNormalizedValue(string(result))
			}
		}
		if resp.ACL == nil {
			r.ACL = nil
		} else {
			r.ACL = &tfTypes.BaseEntityACL{}
			r.ACL.Delete = make([]types.String, 0, len(resp.ACL.Delete))
			for _, v := range resp.ACL.Delete {
				r.ACL.Delete = append(r.ACL.Delete, types.StringValue(v))
			}
			r.ACL.Edit = make([]types.String, 0, len(resp.ACL.Edit))
			for _, v := range resp.ACL.Edit {
				r.ACL.Edit = append(r.ACL.Edit, types.StringValue(v))
			}
			r.ACL.View = make([]types.String, 0, len(resp.ACL.View))
			for _, v := range resp.ACL.View {
				r.ACL.View = append(r.ACL.View, types.StringValue(v))
			}
		}
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		if resp.Files == nil {
			r.Files = nil
		} else {
			r.Files = &tfTypes.BaseRelation{}
			r.Files.DollarRelation = []tfTypes.DollarRelation{}

			for _, dollarRelationItem := range resp.Files.DollarRelation {
				var dollarRelation tfTypes.DollarRelation

				if dollarRelationItem.Tags != nil {
					dollarRelation.Tags = make([]types.String, 0, len(dollarRelationItem.Tags))
					for _, v := range dollarRelationItem.Tags {
						dollarRelation.Tags = append(dollarRelation.Tags, types.StringValue(v))
					}
				}
				dollarRelation.EntityID = types.StringPointerValue(dollarRelationItem.EntityID)

				r.Files.DollarRelation = append(r.Files.DollarRelation, dollarRelation)
			}
		}
		r.ID = types.StringPointerValue(resp.ID)
		r.Manifest = make([]types.String, 0, len(resp.Manifest))
		for _, v := range resp.Manifest {
			r.Manifest = append(r.Manifest, types.StringValue(v))
		}
		r.Org = types.StringValue(resp.Org)
		if resp.Purpose != nil {
			r.Purpose = make([]types.String, 0, len(resp.Purpose))
			for _, v := range resp.Purpose {
				r.Purpose = append(r.Purpose, types.StringValue(v))
			}
		}
		r.Schema = types.StringValue(string(resp.Schema))
		if resp.Tags != nil {
			r.Tags = make([]types.String, 0, len(resp.Tags))
			for _, v := range resp.Tags {
				r.Tags = append(r.Tags, types.StringValue(v))
			}
		}
		r.Title = types.StringPointerValue(resp.Title)
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
		r.Description = types.StringPointerValue(resp.Description)
		if resp.EntityFilters == nil {
			r.EntityFilters = jsontypes.NewNormalizedNull()
		} else {
			entityFiltersResult, _ := json.Marshal(resp.EntityFilters)
			r.EntityFilters = jsontypes.NewNormalizedValue(string(entityFiltersResult))
		}
		r.EntitySchema = types.StringPointerValue(resp.EntitySchema)
		r.Name = types.StringValue(resp.Name)
	}

	return diags
}

func (r *TargetDataSourceModel) ToOperationsGetTargetRequest(ctx context.Context) (*operations.GetTargetRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	hydrate := new(bool)
	if !r.Hydrate.IsUnknown() && !r.Hydrate.IsNull() {
		*hydrate = r.Hydrate.ValueBool()
	} else {
		hydrate = nil
	}
	strict := new(bool)
	if !r.Strict.IsUnknown() && !r.Strict.IsNull() {
		*strict = r.Strict.ValueBool()
	} else {
		strict = nil
	}
	var targetID string
	targetID = r.ID.ValueString()

	out := operations.GetTargetRequest{
		Hydrate:  hydrate,
		Strict:   strict,
		TargetID: targetID,
	}

	return &out, diags
}
